### ISSUE TITLE
Problem with Precision Farming 

### ISSUE THREAD

**Issue by DuckinBoots** [yumi-modding/FS22_CombineXP#13]
The yield that show CombineXP is bigger than game yield,
![fsScreen_2022_04_28_21_57_56](https://user-images.githubusercontent.com/54028622/165850098-28a14b1d-de8d-45af-983e-73ca2af8dfcf.png)

![fsScreen_2022_04_28_21_58_13](https://user-images.githubusercontent.com/54028622/165850092-ef6626bd-0b23-4477-b41a-4ed35fad5255.png)

**Comment by Bohne11297** [comment]
The Yield that is shown in presion farming to low. If you look at the analyzes when the field is finished threshing, you can see that the tons actually harvested are far higher than previously indicated.

**Comment by yumi-modding** [comment]
Hello,
i confirm that yield shown in precision farming info when walking in the field is wrong.
I made a test on Elm Creek on 1 oat field:
- precision farming expects 2.2 T/ha
- Additional Field Info expects 3.99 T/ha (9663 liters for the 1.20 ha field): info available on last commit in github, waiting for test on modhub
- Combine XPerience gives around 4.3 T/ha when harvesting
At the end, in Precision farming map view (+ in my trailer) I get
- 10199 liters (=5,1 T) harvested so a little bit more than what expected by AdditionalField (=> 4.25 T/ha) but closer than what my both mods were giving.
![fsScreen_2022_05_05_10_39_33](https://user-images.githubusercontent.com/23509583/166898292-4558f980-cf6f-4a4f-af28-d6994b516e4a.png)
![fsScreen_2022_05_05_10_41_57](https://user-images.githubusercontent.com/23509583/166898305-fccaa89d-9de6-4ac1-a631-215da8465510.png)
![fsScreen_2022_05_05_11_28_52](https://user-images.githubusercontent.com/23509583/166898310-c2ed21d9-db51-4e25-a2f3-87597d0cf09e.png)
