### ISSUE TITLE
You can mow without turning on the thresher

### ISSUE THREAD

**Issue by KITT3000** [yumi-modding/FS22_CombineXP#15]
Recently, on the MP, friends noticed that you can turn on the header and mow without turning on the chopper, then the particle does not work properly, but there are no restrictions. From the script analysis, I noticed that the `getIsThreshingAllowed` function does not exist in any game script, so overwriting it does nothing, in addition there is probably no condition used with it anywhere.

**Comment by yumi-modding** [comment]
Hello Thanks for the feedback. Could you please tell me which implement you were using so i can check the same scenario. Thanks for the analysis, the code might be only on FS19 or on previous patch maybe.

**Comment by KITT3000** [comment]
In theory, any combine and header, you can check these: #16
