### ISSUE TITLE
LUA error on Dedicated Server

### ISSUE THREAD

**Issue by SbSh-DNA-ModDing** [yumi-modding/FS22_CombineXP#20]
**Describe the bug**
Server won't start complete and reports to log file:

```
Error: Failed to open xml file 'C://gameservers//xyz//ls2022//gameProfile/mods/FS22_CombineXP/data//combineXP.xml'.
Error: Running LUA method 'update'.
C://gameservers//xyz//ls2022//gameProfile/mods/FS22_CombineXP/src/CombineXP.lua:101: bad argument #1 to 'tonumber' (value expected)
```
and if i tried to join the server..:
it couldn't save the combineXP.xml at path mods//FS22_CombineXP/data/combineXP.xml

it seems there is perhaps a issur with / and // slashes in main.lua or combineXP.lua ?

Viele Grüße

ps: hab's versucht zu fixen, aber nun speichert er gar nichts :/

**Comment by yumi-modding** [comment]
Hello
I could not see this issue during my tests even on Dedi server before releasing to modhub.
I will make some new tests on clean server.
Could you please confirm you didn't change anything in the file before getting this error?
Thanks

**Comment by SbSh-DNA-ModDing** [comment]
no, i did edit nothing. I also tested with clean server... modhub and github version. On a clean server is no error there,
but no sync at state 99% loading and 29 % player sync, than it stands still.
Now, i deactivated and deleted the modfile, with keeping the savegame and it still don't sync anymore.
With fresh savegame it works, with combineXP no sync again.
No more tests further I did.

**Comment by yumi-modding** [comment]
Ok thanks, i'll check what the issue is and provide a fix

**Comment by SbSh-DNA-ModDing** [comment]
temporaly I off-commented the saving part, and so i can join and play.. but without saving. nice script and idea. good work.


_-Always try to do everything as precisely as possible, mistakes creep in by themselves._

**Comment by yumi-modding** [comment]
I can reproduce the error on dedi and I am working on a fix.
