### ISSUE TITLE
Combine XP settings not saving

### ISSUE THREAD

**Issue by cwhandersen** [yumi-modding/FS22_CombineXP#22]
When i first downloaded the mod, I started my game set my settings to what I wanted. And then went to harvest my field.
After I've restarted the game I go to harvest again, but I noticed that the settings had reset on the previously used combine.
And after setting my settings again and then restarting, It's reset again. 

And I'm guessing It's supposed to save the setting.

**Comment by yumi-modding** [comment]
As a by-pass, you can create manually a folder named modSettings at the same location than you mods folder so the mod will be able to save.
I will deliver a fix to create it if not existing yet

**Comment by cwhandersen** [comment]
I have a modsettings folder. But there's not a combinexp.xml file. And I can't seem to figure out how to add one of my own.
