### ISSUE TITLE
No issue, just a request

### ISSUE THREAD

**Issue by Michaelj15** [yumi-modding/FS22_CombineXP#26]
Is it possible to make some standard modsettings for the mod?
The mod always returns to normal harvest mode when playing in an existing savegame.
When the setting is changing to realistic, the next time when opening the savegame it's already back to the standard normal mode.

**Comment by yumi-modding** [comment]
Hello,
The version on modhub might suffer from this issue but the last one here commit yesterday should not. Could you please confirm it's ok now at your side?
Thanks

**Comment by Michaelj15** [comment]
Tested it and works indeed with the github version. Thank you!
________________________________
