### ISSUE TITLE
Addition of high yield settings?

### ISSUE THREAD

**Issue by cwhandersen** [yumi-modding/FS22_CombineXP#32]
I would like a high yield setting for this mod. Because of the very slow speeds you can drive with, when you have a 125% yield field with Precision Farming. I get that the speed is realistic for the intake of grain. But it's annoying to drive 2 - 3 km/h on a wheat field.
I would like to drive the appropriate speed for a normal field in real life.

- Harvested crop: Wheat
- Combine and cutter: Lexion 8900 with 9.3 meter header
- Yield: 125%
- Seasons mod activated? Yes
- Time of the day when harvesting: 9:54 am

I was thinking it could be a On/Off  setting like the others. 
Like a Precision Farming Setting.

**Comment by yumi-modding** [comment]
Hello
I think you could first disable the Daytime speed limit setting so you should be able to harvest faster. And then maybe changing to normal or arcade mode should also improve your case.
Please let me know what you think

**Comment by cwhandersen** [comment]
I tried, and it helps a lot. 
Thank you.
