### ISSUE TITLE
Error: Running LUA method 'update'. C:/Users/hriel/OneDrive/Documenten/My Games/FarmingSimulator2022/mods/FS22_CombineXP/src/xpCombine.lua:464: attempt to call method 'getIsTurnedOn' (a nil value)

### ISSUE THREAD

**Issue by Hilbert1982** [yumi-modding/FS22_CombineXP#34]
**Describe the bug**
is start up a saved game and scroll thru my vehicles to start. wenn i tab in to my forager the game stops and shows this error in the log file:
Error: Running LUA method 'update'.
C:/Users/hriel/OneDrive/Documenten/My Games/FarmingSimulator2022/mods/FS22_CombineXP/src/xpCombine.lua:464: attempt to call method 'getIsTurnedOn' (a nil value)

**To Reproduce**
Details to reproduce the behavior:
- Harvested crop:didn't get so far
- Combine and cutter:fendt katana with krone pick-up and elmars haulmaster (all ingame stuff)
- Yield: -
- Seasons mod activated? bases game
- Time of the day when harvesting: morning

**Screenshots**

**Additional context**

**Comment by Hilbert1982** [comment]
[errorlog.txt](https://github.com/yumi-modding/FS22_CombineXP/files/9542272/errorlog.txt)

**Comment by yumi-modding** [comment]
Hello,
Thank for the feedback. I was not able to reproduce the issue even I can maybe see some wrong code at this line. I will try again tomorrow, maybe it's due to a conflict that i've not identified yet.

**Comment by Hilbert1982** [comment]
![start game ok](https://user-images.githubusercontent.com/97124680/189545651-f7ea8f2c-cbdc-4502-9dc6-a7b4a2ad2314.png)
![ingame](https://user-images.githubusercontent.com/97124680/189545658-55b53526-978d-49ea-97bb-fc565e7952fa.png)

![no problem in game](https://user-images.githubusercontent.com/97124680/189545660-ac4ed539-4dbc-4bdb-a974-bd64a54924b0.png)
![problem starts with hitting q](https://user-images.githubusercontent.com/97124680/189545667-f9ee8601-2197-4d18-81bd-471857fc6bdd.png)

**Comment by Hilbert1982** [comment]
so i started with a empty modfolder and only combinexp is in there.
With start-up no problem --> i buy original katana grass pick-up and elmer--> stil no problem--> connect pick_up no problem as soon as you try to connect the grain cart the problem pops up. (i know it's not meant to fit to getter butt for me it's the only way to have a decent time to pick up some grass without playing weaks.

**Comment by Hilbert1982** [comment]
![different cart](https://user-images.githubusercontent.com/97124680/189545941-94baedc6-613e-4b4e-a45c-729665b014a8.png)

**Comment by Hilbert1982** [comment]
![combine same problem](https://user-images.githubusercontent.com/97124680/189546097-f31f5a6b-6f91-455d-9e1a-30e5e9952fa7.png)

**Comment by yumi-modding** [comment]
Ok thanks for the details that will help a lot.

**Comment by Hilbert1982** [comment]
thanks for the good work. it works really nice
