### ISSUE TITLE
translation to portuguese from brazil

### ISSUE THREAD

**Issue by leo32128fs** [yumi-modding/FS22_CombineXP#4]
[modDesc.zip](https://github.com/yumi-modding/FS22_CombineXP/files/7715336/modDesc.zip)

small translation to brazilian portuguese, many brazilians use your mod which is certainly one of the best mods for FS , thanks!

**Comment by yumi-modding** [comment]
Hello @leo32128fs I updated modDesc with your changes. Thanks for your support.
Please let me know if setGameplay translation is ok since i added some text

**Comment by leo32128fs** [comment]
The added lines are in the correct translation are OK , and again thanks for this amazing mod it helps a lot the game to be more realistic

**Comment by yumi-modding** [comment]
Merged via commit 93af35686930fe17e0f01ec2c52851ad8c580c1d
