### ISSUE TITLE
Q: possibility to move ingame HUD?

### ISSUE THREAD

**Issue by mrPassion78** [yumi-modding/FS22_CombineXP#46]
is there a way to slightly move the in-game HUD more to the left.
The problem now is that in partially overlap the CVT Addon hud..witch is next to the speed Hud.
![fsScreen_2023_11_23_08_59_37](https://github.com/yumi-modding/FS22_CombineXP/assets/40406761/513de4cc-7102-405d-b910-5cc30225d808)

**Comment by Nightcloak** [comment]
Hi,
i hope its ok to post this here but you can join the discord of the maker of the CVT addon
he has a fix for this very issue
https://discord.com/channels/660942481118199811/1137738058628862053

**Comment by SbSh-DNA-ModDing** [comment]
https://github.com/yumi-modding/FS22_CombineXP/pull/42

**Comment by mrPassion78** [comment]
the discord fix worked.. thnx.. i`ll close this now.
