### ISSUE TITLE
Lua Error while using Krone BigX for cutting grass (realSpeedLimit mod conflict)

### ISSUE THREAD

**Issue by BarnyHarz** [yumi-modding/FS22_CombineXP#7]
**Describe the bug**
When i try to use the Krone BigX with Easyflow 300 to cut mowed swathed grass I get the following lua.error:
2021-12-23 13:10 Error: Running LUA method 'update'.
C:/Users/Barnabas/Documents/My Games/FarmingSimulator2022/mods/FS22_CombineXP/src/xpCombine.lua:411: bad argument #1 to 'min' (number expected, got nil).
The Combine and cutter do not work and the cutter is losing very fast his over all status for repairing.
Everything on Erlengrat in LS22

**To Reproduce**
Details to reproduce the behavior:
- Harvested crop: Grass
- Combine and cutter: Krone BigX and Easyflow 300
- Yield:
- Seasons mod activated?
- Time of the day when harvesting: Every time

**Screenshots**

**Additional context**

**Comment by yumi-modding** [comment]
Hello,

I tried to reproduce your issue on Haut-Beyleron and Erlengrat with BigX1180 & Easyflow 300 but I'm not able get this error.
Are you using any mod (for the BigX or Easyflow) or script mod that could have changed/removed the default speedLimit that is set in the xml files ?
![fsScreen_2021_12_23_23_28_33](https://user-images.githubusercontent.com/23509583/147296451-fb1154eb-8bf8-4d1c-8dda-53890588dce6.png)
![fsScreen_2021_12_23_23_20_42](https://user-images.githubusercontent.com/23509583/147296453-34cfc740-d0be-44a0-afd1-8f8bab2ecdba.png)

**Comment by BarnyHarz** [comment]
Hello yumi,

I think I found the conflicting mod. It was RealSpeedLimit from the hub which was conflicting the script of CombineXP

**Comment by yumi-modding** [comment]
Hello @BarnyHarz ,
Thanks. I will try this mod and push a piece of code to avoid the error anyway.

**Comment by yumi-modding** [comment]
Hello @BarnyHarz
I confirm it's due to realSpeedLimit mod conflict. I will deliver a fix so people can use both if they like.

**Comment by vitalii2011** [comment]
I don't know if this is worth a new thread: `Error: Could not save xml file 'combineXP' to 'C:/Users/…/Documents/My Games/FarmingSimulator2022/mods/FS22_CombineXP/data/combineXP.xml'`

**Comment by jason0611** [comment]
Hello yumi,
today I investigated I little bit in this issue: Both mods are overwriting the same function, vehicle:getSpeedLimit. So I fear, this mod conflict will not be solvable. 
As a workaround for myself I modified realSpeedLimit to no longer register into combines, but this is only helpful if you are using both mods.
Regards, 
Martin

**Comment by yumi-modding** [comment]
Thanks, that could be an idea. I think i can maybe tell that for combines RSL getSpeedLimit overwrite does nothing. Need to test

**Comment by JimmyBeam1990** [comment]
hi, are there any changes yet? because we also use both mods on a Dedi server and when we want to chop grass the chopper only goes 3 kmh

Mod: FS22_adjustWorkingSpeed.zip v2.1.0.0

edit: after the removal of: FS22_adjustWorkingSpeed, the Fendt Katana 65 and Kemper P3003 still only drives 3 Kmh around harvest mode.

edit2: never mind, the fendt katana is a private mod, it is not stored in combineXP.xml

**Comment by DrewCZ** [comment]
Hi, I've got a similar error with speed: 
```
2022-08-24 20:45 Error: Running LUA method 'update'.
D:/DataTata/FarmMods22/FS22_CombineXP/src/xpCombine.lua:420: bad argument #1 to 'min' (number expected, got nil)
```
RealSpeed already deleted 
observed on E-516 mod from GS modHub
thank you for any advices
help please
