### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by Blackjack155** [yumi-modding/FS22_CombineXP#9]
Will the mod be further developed? :)

**Comment by yumi-modding** [comment]
Hello,
Yes I'm waiting for modhub validation before adding new things here.

**Comment by Blackjack155** [comment]
okay great I wanted to mod eigl konvenieren because you still do it but I'm all the more pleased
is your native language?

or do they have a Discord to communicate?

**Comment by yumi-modding** [comment]
Yes you can find me on discord yumi#9522

**Comment by Blackjack155** [comment]
is out
